Test: randoop.synoptic.RandoopTest2.test342
Intended behavior: FAILURE
when executed after: [randoop.synoptic.RandoopTest1.test423]
The revealed different behavior: PASS
when executed after: []

Test: randoop.synoptic.RandoopTest1.test78
Intended behavior: FAILURE
when executed after: []
The revealed different behavior: PASS
when executed after: [randoop.synoptic.RandoopTest3.test245]

Test: randoop.synoptic.RandoopTest2.test107
Intended behavior: FAILURE
when executed after: [randoop.synoptic.RandoopTest1.test423]
The revealed different behavior: PASS
when executed after: []

