Test: randoop.jodatime.RandoopTest2.test490
Intended behavior: FAILURE
when executed after: [randoop.jodatime.RandoopTest2.test487]
The revealed different behavior: PASS
when executed after: []

Test: randoop.jodatime.RandoopTest2.test487
Intended behavior: FAILURE
when executed after: [randoop.jodatime.RandoopTest2.test356]
The revealed different behavior: PASS
when executed after: []

Test: randoop.jodatime.RandoopTest2.test356
Intended behavior: FAILURE
when executed after: [randoop.jodatime.RandoopTest0.test498]
The revealed different behavior: PASS
when executed after: []

